version: '3.2'
services:
  db:
    image: mysql:5.7
    container_name: todo_mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    ports:
      - '3306:3306'
    volumes:
      - ./backups:/backups